config/routes.rb
Flockr::Application.routes.draw do
  root 'home#index'
  
  get '/sign_up' => 'users#new'
  
  resources :users do
    resources :photos
  end
  

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save do
    self.email = email.downcase
    self.username = username.downcase
  end
  
  has_many :photos, dependent: :destroy
  has_secure_password
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => VALID_EMAIL_REGEX
  validates_presence_of :username
  validates_uniqueness_of :username
  validates_length_of :password, :minimum => 6
  validates_confirmation_of :password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  
  # GET /photos
  # GET /photos.json
  def index
    @photos = @user.photos
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = @user.photos.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = @user.photos.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to user_photo_path(@user, @photo), notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to user_photo_path(@user, @photo), notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to user_photos_url(@user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end
    
    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:file_name, :path, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Welcome to Flockr #{@user.username}!" }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome to Flockr</h1>
<p>We have the photos.</p>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <a class="navbar-brand" href="/">Flockr</a>
  </div>

  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <% if request.path == users_path %>
          <li class="active"><%= link_to 'Users', users_path %></li>
      <% else %>
          <li><%= link_to 'Users', users_path %></li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if request.path == sign_up_path %>
          <li class="active"><%= link_to 'Sign Up', sign_up_path %></li>
      <% else %>
          <li><%= link_to 'Sign Up', sign_up_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flockr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  
  <%= render 'layouts/navbar' %>

  <%= yield %>
  
</div>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo, url: user_photo_path(@user, @photo)) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_name %><br>
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', user_photo_path(@user, @photo) %> |
<%= link_to 'Back', user_photos_path(@user) %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <thead>
    <tr>
      <th>File name</th>
      <th>Path</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.file_name %></td>
        <td><%= image_tag(photo.path) %></td>
        <td><%= link_to 'Show', user_photo_path(@user, photo) %></td>
        <td><%= link_to 'Edit', edit_user_photo_path(@user, photo) %></td>
        <td><%= link_to 'Destroy', user_photo_path(@user, photo), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_user_photo_path(@user) %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', user_photos_path(@user) %> %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File name:</strong>
  <%= @photo.file_name %>
</p>

<p>
  <strong>Path:</strong>
  <%= @photo.path %>
</p>

<%= link_to 'Edit', edit_user_photo_path(@user, @photo) %> |
<%= link_to 'Back', user_photos_path(@user) %>

app/views/users/_form.html.erb
<%= form_for(@user, role: 'form') do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :username %><br>
    <%= f.text_field :username, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'Confirmation' %><br>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Sign Up', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<hr/>

<div class="row">
  <div class="col-md-1">
  </div>

  <div class="col-md-4">
    <%= render 'form' %>
  </div>
</div>

<hr/>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<hr/>

<div class="row">
  <div class="col-md-6">

    <table class="table table-striped table-hover table-condensed">
      <thead>
      <tr>
        <th>Email</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= link_to 'Show', user, class: 'btn btn-default btn-xs' %></td>
            <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-warning btn-xs' %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<hr/>

<div class="row">
  <div class="col-md-1">
  </div>

  <div class="col-md-4">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.username %></h1>

<hr/>

<div class="row">
  <div class="col-md-6">
    <table class="table">
      <tbody>
      <tr>
        <td><strong>Email:</strong></td>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <td><strong>Member since:</strong></td>
        <td><%= time_ago_in_words(@user.created_at) %></td>
      </tr>
      </tbody>
      <tr>
        <td>
          <%= link_to 'Photos', user_photos_path(@user), class: 'btn btn-primary' %>
        </td>
        <td></td>
      </tr>
    </table>

    <%= link_to edit_user_path(@user) do %>
        <button type="button" class="btn btn-default btn-xs">
          <span class="glyphicon glyphicon-cog"></span>
          Edit
        </button>
    <% end %>
    <%= link_to users_path do %>
        <button type="button" class="btn btn-default btn-xs">
          <span class="glyphicon glyphicon-backward"></span>
          Back
        </button>
    <% end %>
  </div>
</div>